dna = input("Введите последовательность ДНК: ")
dna_upper = dna.upper()
a = dna_upper.count("A")
t = dna_upper.count("T")
g = dna_upper.count("G")
c = dna_upper.count("C")
length = len(dna_upper)
print("\n=== Анализ последовательности ДНК ===\n")
print(f"Последовательность в верхнем регистре: {dna_upper}\n")
print("Подсчёт нуклеотидов:")
print(f"A: {a}")
print(f"T: {t}")
print(f"G: {g}")
print(f"C: {c}\n")
print(f"Общая длина: {length} нуклеотидов")