name = input("Введите ФИО: ")
date = input("Введите дату: ")
experiment = input("Введите название эксперимента: ")
result = input("Введите вывод: ")
with open("journal.txt", "w") as file:
    file.write("+-----------------------------------+\n")
    file.write("| Электронный лабораторный журнал    |\n")
    file.write("+-----------------------------------+\n")
    file.write(f"| ФИО исследователя: {name}\n")
    file.write(f"| Дата: {date}\n")
    file.write(f"| Эксперимент: {experiment}\n")
    file.write("+-----------------------------------+\n")
    file.write("| Вывод:\n")
    file.write(f"| {result}\n")
    file.write("+-----------------------------------+\n")
print("Данные сохранены в journal.txt")